name: .NET

on:
  push:
    branches: [ "develop", "feature/**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Stott.Optimizely.RobotsHandler.sln
    - name: Build
      run: dotnet build src/Stott.Optimizely.RobotsHandler.sln --no-restore
    - name: Test
      run: dotnet test src/Stott.Optimizely.RobotsHandler.sln --no-build --verbosity normal
